# **04 Data Preprocessing dengan Sckit-Learn**

**Sample Dataset** <br>
- Dataset ini terdiri dari 4 baris data, dan setiap barisnya memiliki 3 fitur.
- Fungsi .shape digunakan untuk mengetahui dimensi dari dataset. Output berupa nilai 4,3 menunjukkan bahwa dataset ini terdiri dari 4 baris dan 3 fitur.

In [4]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5], 
                        [-1.5, 2.4, 3.5], 
                        [0.5, -7.9, 5.6],
                        [5.9, 2.3, -5.8]])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [6]:
sample_data.shape

(4, 3)

**Binarisation** <br>
- Proses binarisasi menghasilkan output yang terdiri dari nilai 0 dan 1 saja.
- Binarizer dapat diaplikasikan dengan menggunakan fungsi preprocessing.Binarizer()
- Parameter threshold menentukan nilai batas yang akan dijadikan 0, sedangkan nilai di atasnya akan diubah menjadi nilai 1 dan untuk nilai yang sama dengan treshold akan di konversi menjadi 0
- .Fungsi transform() digunakan untuk mengubah data sampel menjadi nilai biner.

In [9]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [11]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

**Scaling** <br>
- Tujuan scaling adalah mengubah nilai data numerik sehingga berada dalam rentang tertentu.uProses ini dapat dilakukan dengan menggunakan fungsi preprocessing.MinMaxScaler().Tentukan jangkauan scaling.
- Setelahnya kita sesuaikan sample_data dengan scaler tadi menggunakan fungsi fit().
- Terakhir transform sample_data menggunakan method transform().
- Penyingkatan cara kedua dan ketiga bisa dilakukan dengan menggunkan method fit_transform().

In [18]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [20]:
preprocessor = preprocessing.MinMaxScaler(feature_range=(0, 1))
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [22]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

**L1 Noemalisation : Least Absolute Deviations** <br>
Referensi : [wikipedia](https://en.wikipedia.org/wiki/Least_absolute_deviations) <br>
Melakukan normalisasi nilai numerik dapat menggunakan fungsi preprocessing.normalize()

In [27]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [31]:
l1_normalised_data = preprocessing.normalize(sample_data, norm='l1')
l1_normalised_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

**L2 Normalisation : Least Squares** <br>
Referensi : [wikipedia](https://en.wikipedia.org/wiki/Least_squares) <br>
Melakukan normalisasi nilai numerik dapat menggunakan fungsi preprocessing.normalize()

In [35]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [37]:
l2_normalised_data = preprocessing.normalize(sample_data, norm='l2')
l2_normalised_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.68706914,  0.26784051, -0.6754239 ]])